apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    curso: gitops
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 28.13.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/prometheus/values.yml
    - repoURL: https://github.com/YagoCastilho/web-page-deploy.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring